services:
  database_server:
    build:
      context: ./scripts/docker/database
      dockerfile: ./Dockerfile
      args:
        POSTGRESQL_MAJOR_VERSION: ${POSTGRESQL_MAJOR_VERSION}
        POSTGRESQL_MINOR_VERSION: ${POSTGRESQL_MINOR_VERSION}
    container_name: "container_${DATABASE_SERVER_ALTERNATE_HOSTNAME}"
    user: 123:129
    environment:
      POSTGRES_USER: ${DATABASE_ADMIN_USER}
      POSTGRES_PASSWORD: ${DATABASE_ADMIN_ROLE_PASSWORD}
      PGDATA: /var/lib/postgresql/${POSTGRESQL_MAJOR_VERSION}/docker
      CA_CRT: ${CA_CRT}
      POSTGRESQL_MAJOR_VERSION: ${POSTGRESQL_MAJOR_VERSION}
      DATABASE_ADMIN_USER: ${DATABASE_ADMIN_USER}
      DATABASE_SERVER_KEY_WITHOUT_PASSWORD: ${DATABASE_SERVER_KEY_WITHOUT_PASSWORD}
      DATABASE_SERVER_CRT: ${DATABASE_SERVER_CRT}
      DATABASE_ADMIN_KEY: ${DATABASE_ADMIN_KEY}
      DATABASE_ADMIN_KEY_PASSWORD: ${DATABASE_ADMIN_KEY_PASSWORD}
      DATABASE_ADMIN_CRT: ${DATABASE_ADMIN_CRT}
      DATABASE_NAME: ${DATABASE_NAME}
      APP_ROLE: ${APP_ROLE}
      APP_ROLE_PASSWORD: ${APP_ROLE_PASSWORD}
    volumes:
      - ${DATABASE_ADMIN_HOME}:/var/lib/postgresql:rw
    ports:
      - "127.0.0.1:5433:5432"

  keyword_dataset_bot:
    build:
      context: ./
      dockerfile: ./scripts/docker/app/Dockerfile
      args:
        ARTIFACT_ID: ${ARTIFACT_ID}
        APP_CERTS_DIRECTORY: ${APP_CERTS_DIRECTORY}
        APP_AUDIO_DIRECTORY: ${APP_AUDIO_DIRECTORY}
    container_name: "container_${APP_NAME}"
    user: 1000:1000
    environment:
      ARTIFACT_ID: ${ARTIFACT_ID}
      BOT_TOKEN: ${BOT_TOKEN}
      VOICE_EXTENSION: ${VOICE_EXTENSION}
      DATABASE_SERVER_URL: ${DATABASE_SERVER_URL}
      APP_ROLE: ${APP_ROLE}
      APP_ROLE_PASSWORD: ${APP_ROLE_PASSWORD}
      APP_CERTS_DIRECTORY: ${APP_CERTS_DIRECTORY}
      APP_AUDIO_DIRECTORY: ${APP_AUDIO_DIRECTORY}
      APP_DER_KEY: ${APP_DER_KEY}
      APP_KEY_PASSWORD: ${APP_KEY_PASSWORD}
      APP_CRT: ${APP_CRT}
      CA_CRT: ${CA_CRT}
    volumes:
      - ${APP_CERTS_DIRECTORY}:${APP_CERTS_DIRECTORY}:r
      - ${APP_AUDIO_DIRECTORY}:${APP_AUDIO_DIRECTORY}:rw
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - ${DATABASE_SERVER_ALTERNATE_HOSTNAME}

#TODO add user for app
#TODO dont hardcode user UID and GID
#TODO dont hardcode service names
#TODO maybe generate this file