version: '3.8'

services:
  database_server:
    build:
      context: ./scripts/docker
      args:
        DATABASE_SERVER_USER: ${DATABASE_SERVER_USER}
        DATABASE_SERVER_KEY_WITHOUT_PASSWORD: ${DATABASE_SERVER_KEY_WITHOUT_PASSWORD}
        DATABASE_SERVER_CRT: ${DATABASE_SERVER_CRT}
        CA_CRT: ${CA_CRT}
        DATABASE_NAME: ${DATABASE_NAME}
        CLIENT_APP_ROLE: ${CLIENT_APP_ROLE}
    container_name: ${DATABASE_SERVER_ALTERNATE_HOSTNAME}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/16/docker
      CLIENT_APP_ROLE: ${CLIENT_APP_ROLE}
      CLIENT_APP_PASSWORD: ${CLIENT_APP_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - ./scripts/docker/certs:/certs:ro
      - /var/lib/postgresql_docker:/var/lib/postgresql:rw
    user: 123:129

  keyword_dataset_bot:
    build:
      context: ./scripts/docker_app
      args:
        CLIENT_APP_USER_HOME: ${CLIENT_APP_USER_HOME}
    container_name: ${CLIENT_APP_USER}
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      VOICE_EXTENSION: ${VOICE_EXTENSION}
      DATABASE_SERVER_URL: ${DATABASE_SERVER_URL}
      CLIENT_APP_USER: ${CLIENT_APP_USER}
      CLIENT_APP_USER_UID: 125
      CLIENT_APP_USER_GID: 131
      CLIENT_APP_ROLE: ${CLIENT_APP_ROLE}
      CLIENT_APP_PASSWORD: ${CLIENT_APP_PASSWORD}
      CLIENT_APP_USER_HOME: ${CLIENT_APP_USER_HOME}
      CLIENT_APP_AUDIO_DIRECTORY: ${CLIENT_APP_AUDIO_DIRECTORY}
      CLIENT_APP_CERTS_DIRECTORY: ${CLIENT_APP_CERTS_DIRECTORY}
      CLIENT_APP_DER_KEY: ${CLIENT_APP_DER_KEY}
      CLIENT_APP_KEY_PASSWORD: ${CLIENT_APP_KEY_PASSWORD}
      CLIENT_APP_CRT: ${CLIENT_APP_CRT}
      CA_CRT: ${CA_CRT}
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./scripts/docker_app/certs:/${CLIENT_APP_CERTS_DIRECTORY}:ro
      - ${CLIENT_APP_AUDIO_DIRECTORY}:${CLIENT_APP_AUDIO_DIRECTORY}:rw
    depends_on:
      - ${DATABASE_SERVER_ALTERNATE_HOSTNAME}

#TODO add user for app
#TODO dont hardcode user UID and GID
#TODO dont hardcode service names
#TODO maybe generate this file