sudo \
-u "${CLIENT_APP_USER}" \
psql "postgresql://${CLIENT_APP_ROLE}:${CLIENT_APP_PASSWORD}@${DATABASE_SERVER_HOSTNAME}:5432/${DATABASE_NAME}?sslcertmode=require&sslmode=verify-full&sslkey=${CLIENT_APP_CERTS_DIRECTORY}/${CLIENT_APP_KEY}&sslpassword=${CLIENT_APP_KEY_PASSWORD}&sslcert=${CLIENT_APP_CERTS_DIRECTORY}/${CLIENT_APP_CRT}&sslrootcert=${CLIENT_APP_CERTS_DIRECTORY}/${CA_CRT}"